### ISSUE TITLE
Research on Cloud Technology - Serverless & Pricing

### ISSUE THREAD

**Issue by HanyuXi** [HanyuXi/TravelProject#2]

**Comment by krshnpatel** [comment]
[Full-stack app with Serverless (React/Dynamo)](https://serverless-stack.com/#the-basics)
[REST API with Serverless/Node.js/MongoDB](https://hackernoon.com/building-a-serverless-rest-api-with-node-js-and-mongodb-2e0ed0638f47)

**Comment by krshnpatel** [comment]
I setup a quick Serverless project locally and it is very promising and simple to use.
